name: Approve PRs

on:
  pull_request:
    types: [labeled]
    
jobs:
  approval:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'safe-to-test')
    steps:
      - run: echo test
