name: Lint

on: [pull_request, workflow_dispatch]

jobs:
  terraform-fmt:
      name: terraform fmt
      runs-on: ubuntu-latest

      steps:
      - name: Checkout
        run: |
          curl \
          -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=api://AzureADTokenExchange"
        
