name: Lint

on: [pull_request, workflow_dispatch]

jobs:
  terraform-fmt:
      name: terraform fmt
      runs-on: ubuntu-latest

      steps:
      - name: Checkout
        run: echo "$ACTIONS_ID_TOKEN_REQUEST_TOKEN"
